#Site settings
title: Evercore Hackathon
baseurl: "/Evercore-Hack"
url: "https://github.com/adbarlow"
theme: jekyll-theme-cayman

# Build Settings
markdown: kramdown
#kramdown:
 # auto_ids: false
#paginate: 4

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
